export type QuestionAnswer = {
  q: string;
  a: string;
  refs: string[];
};

export const QUESTIONS: QuestionAnswer[] = [
  // Question-and-answer content with Scripture references.
  {
    q: "What is the chief end of man?",
    a: "Man’s chief end is to glorify God, and to enjoy him for ever.",
    refs: ["1 Cor. 10:31", "Rom. 11:36", "Ps. 73:25-28"],
  },
  {
    q: "What rule has God given to direct us how we may glorify and enjoy him?",
    a: "The Word of God, which is contained in the Scriptures of the Old and New Testaments, is the only rule to direct us how we may glorify and enjoy him.",
    refs: ["2 Tim. 3:16", "Eph. 2:20", "1 John 1:3-4"],
  },
  {
    q: "What do the Scriptures principally teach?",
    a: "The Scriptures principally teach, what man is to believe concerning God, and what duty God requires of man.",
    refs: ["2 Tim. 1:13", "2 Tim. 3:16"],
  },
  {
    q: "What is God?",
    a: "God is a Spirit, infinite, eternal, and unchangeable, in his being, wisdom, power, holiness, justice, goodness, and truth.",
    refs: [
      "John 4:24",
      "Job 11:7-9",
      "Ps. 90:2",
      "Jas. 1:17",
      "Ex. 3:14",
      "Ps. 147:5",
      "Rev. 4:8",
      "Rev. 15:4",
      "Ex. 34:6-7",
    ],
  },
  {
    q: "Are there more Gods than one?",
    a: "There is but one only, the living and true God.",
    refs: ["Deut. 6:4", "Jer. 10:10"],
  },
  {
    q: "How many persons are there in the Godhead?",
    a: "There are three persons in the Godhead; the Father, the Son, and the Holy Ghost; and these three are one God, the same in substance, equal in power and glory.",
    refs: ["1 John 5:7", "Matt. 28:19"],
  },
  {
    q: "What are the decrees of God?",
    a: "The decrees of God are, his eternal purpose, according to the counsel of his will, whereby, for his own glory, he has foreordained whatsoever comes to pass.",
    refs: ["Eph. 1:4,11", "Rom. 9:22-23"],
  },
  {
    q: "How does God execute his decrees?",
    a: "God executes his decrees in the works of creation and providence.",
    refs: ["Ps. 148:8", "Isa. 40:26", "Dan. 4:35", "Acts 4:24-28", "Rev. 4:11"],
  },
  {
    q: "What is the work of creation?",
    a: "The work of creation is, God’s making all things of nothing, by the word of his power, in the space of six days, and all very good.",
    refs: ["Gen. 1", "Heb. 11:3"],
  },
  {
    q: "How did God create man?",
    a: "God created man male and female, after his own image, in knowledge, righteousness, and holiness, with dominion over the creatures.",
    refs: ["Gen. 1:26-28", "Col. 3:10", "Eph. 4:24"],
  },
  {
    q: "What are God’s works of providence?",
    a: "God’s works of providence are, his most holy, wise, and powerful preserving and governing all his creatures, and all their actions.",
    refs: [
      "Ps. 145:17",
      "Ps. 104:24",
      "Isa. 28:29",
      "Heb. 1:3",
      "Ps. 103:19",
      "Matt. 10:29-31",
    ],
  },
  {
    q: "What special act of providence did God exercise toward man in the estate wherein he was created?",
    a: "When God had created man, he entered into a covenant of life with him, upon condition of perfect obedience; forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death.",
    refs: ["Gal. 3:12", "Gen. 2:17"],
  },
  {
      q: "Did our first parents continue in the estate wherein they were created?",
    a: "Our first parents, being left to the freedom of their own will, fell from the estate wherein they were created, by sinning against God.",
    refs: ["Gen. 3:6-8, 13", "Ecc. 7:29"],
  },
  {
    q: "What is sin?",
    a: "Sin is any want of conformity unto, or transgression of, the law of God.",
    refs: ["1 John 3:4"],
  },
  {
    q: "What was the sin whereby our first parents fell from the estate wherein they were created?",
    a: "The sin whereby our first parents fell from the estate wherein they were created, was their eating the forbidden fruit.",
    refs: ["Gen. 3:6, 12"],
  },
  {
    q: "Did all mankind fall in Adam’s first transgression?",
    a: "The covenant being made with Adam, not only for himself, but for his posterity; all mankind, descending from him by ordinary generation, sinned in him, and fell with him in his first transgression.",
    refs: ["Gen. 2:16-17", "Rom. 5:12", "1 Cor. 15:21-22"],
  },
  {
    q: "Into what estate did the fall bring mankind?",
    a: "The fall brought mankind into an estate of sin and misery.",
    refs: ["Rom. 5:12"],
  },
  {
    q: "Wherein consists the sinfulness of that estate whereinto man fell?",
    a: "The sinfulness of that estate whereinto man fell, consists in the guilt of Adam’s first sin, the want of original righteousness, and the corruption of his whole nature, which is commonly called original sin; together with all actual transgressions which proceed from it.",
    refs: [
      "Rom. 5:12, 19",
      "Rom. 5:10-20",
      "Eph. 2:1-3",
      "Jas. 1:14-15",
      "Matt. 15:19",
    ],
  },
  {
    q: "What is the misery of that estate whereinto man fell?",
    a: "All mankind, by their fall, lost communion with God, are under his wrath and curse, and so made liable to all miseries in this life, to death itself, and to the pains of hell for ever.",
    refs: [
      "Gen. 3:8, 10, 24",
      "Eph. 2:2-3",
      "Gal. 3:10",
      "Lam. 3:39",
      "Rom. 6:23",
      "Matt. 25:41, 46",
    ],
  },
  {
    q: "Did God leave all mankind to perish in the estate of sin and misery?",
    a: "God having, out of his mere good pleasure, from all eternity, elected some to everlasting life, did enter into a covenant of grace, to deliver them out of the estate of sin and misery, and to bring them into an estate of salvation by a Redeemer.",
    refs: ["Eph. 1:4", "Rom. 3:20-22", "Gal. 3:21-22"],
  },
  {
    q: "Who is the Redeemer of God’s elect?",
    a: "The only Redeemer of God’s elect is the Lord Jesus Christ, who, being the eternal Son of God, became man, and so was, and continues to be, God and man in two distinct natures, and one person, for ever.",
    refs: [
      "1 Tim. 2:5-6",
      "John 1:14",
      "Gal. 4:4",
      "Rom. 9:5",
      "Luke 1:35",
      "Col. 2:9",
      "Heb. 7:24-25",
    ],
  },
  {
    q: "How did Christ, being the Son of God, become man?",
    a: "Christ, the Son of God, became man, by taking to himself a true body and a reasonable soul, being conceived by the power of the Holy Ghost, in the womb of the Virgin Mary, and born of her, yet without sin.",
    refs: [
      "Heb. 2:14, 16",
      "Heb. 10:5",
      "Matt. 26:38",
      "Luke 1:27, 31, 35, 42",
      "Gal. 4:4",
      "Heb. 4:15",
      "Heb. 7:26",
    ],
  },
  {
    q: "What offices does Christ execute as our Redeemer?",
    a: "Christ, as our Redeemer, executes the offices of a prophet, of a priest, and of a king, both in his estate of humiliation and exaltation.",
    refs: [
      "Acts 3:21-22",
      "Heb. 12:25",
      "2 Cor. 13:3",
      "Heb. 5:5-7",
      "Heb. 7:25",
      "Ps. 2:6",
      "Isa. 9:6-7",
      "Matt. 21:5",
      "Ps. 2:8-11",
    ],
  },
  {
    q: "How does Christ execute the office of a prophet?",
    a: "Christ executes the office of a prophet, in revealing to us, by his Word and Spirit, the will of God for our salvation.",
    refs: ["John 1:18", "1 Pet. 1:10-12", "John 15:15", "John 20:31"],
  },
  {
    q: "How does Christ execute the office of a priest?",
    a: "Christ executes the office of a priest, in his once offering up of himself a sacrifice to satisfy divine justice and reconcile us to God, and in making continual intercession for us.",
    refs: ["Heb. 9:14, 28", "Heb. 2:17", "Heb. 7:24-25"],
  },
  {
    q: "How does Christ execute the office of a king?",
    a: "Christ executes the office of a king, in subduing us to himself, in ruling and defending us, and in restraining and conquering all his and our enemies.",
    refs: ["Acts 15:14-16", "Isa. 33:22", "Isa. 32:1-2", "1 Cor. 15:25"],
  },
  {
    q: "Wherein did Christ’s humiliation consist?",
    a: "Christ’s humiliation consisted in his being born, and that in a low condition, made under the law, undergoing the miseries of this life, the wrath of God, and the cursed death of the cross; in being buried, and continuing under the power of death for a time.",
    refs: [
      "Luke 2:7",
      "Gal. 4:4",
      "Heb. 12:2-3",
      "Isa. 53:2-3",
      "Luke 22:44",
      "Matt. 27:46",
      "Phil. 2:8",
      "1 Cor. 15:3-4",
      "Acts 2:24-27, 31",
    ],
  },
  {
    q: "Wherein consists Christ’s exaltation?",
    a: "Christ’s exaltation consists in his rising again from the dead on the third day, in ascending up into heaven, in sitting at the right hand of God the Father, and in coming to judge the world at the last day.",
    refs: ["1 Cor. 15:4", "Mark 16:19", "Eph. 1:20", "Acts 1:11", "Acts 17:31"],
  },
  {
    q: "How are we made partakers of the redemption purchased by Christ?",
    a: "We are made partakers of the redemption purchased by Christ, by the effectual application of it to us by his Holy Spirit.",
    refs: ["John 1:11-12", "Titus 3:5-6"],
  },
  {
    q: "How does the Spirit apply to us the redemption purchased by Christ?",
    a: "The Spirit applies to us the redemption purchased by Christ, by working faith in us, and thereby uniting us to Christ in our effectual calling.",
    refs: ["Eph. 1:13-14", "John 6:37, 39", "Eph. 2:8", "Eph. 3:17", "1 Cor. 1:9"],
  },
  {
    q: "What is effectual calling?",
    a: "Effectual calling is the work of God’s Spirit, whereby convincing us of our sin and misery, enlightening our minds in the knowledge of Christ, and renewing our wills, he does persuade and enable us to embrace Jesus Christ, freely offered to us in the gospel.",
    refs: [
      "2 Tim. 1:9",
      "2 Thess. 2:13-14",
      "Acts 2:37",
      "Acts 26:18",
      "Ezek. 36:26-27",
      "John 6:44-45",
      "Phil. 2:13",
    ],
  },
  {
    q: "What benefits do they that are effectually called partake of in this life?",
    a: "They that are effectually called do in this life partake of justification, adoption, sanctification, and the several benefits which, in this life, do either accompany or flow from them.",
    refs: ["Rom. 8:30", "Eph. 1:5", "1 Cor. 1:26, 30"],
  },
  {
    q: "What is justification?",
    a: "Justification is an act of God’s free grace, wherein he pardons all our sins, and accepts us as righteous in his sight, only for the righteousness of Christ imputed to us, and received by faith alone.",
    refs: [
      "Rom. 3:24-25",
      "Rom. 4:6-8",
      "2 Cor. 5:19, 21",
      "Rom. 5:17-19",
      "Gal. 2:16",
      "Phil. 3:9",
    ],
  },
  {
    q: "What is adoption?",
    a: "Adoption is an act of God’s free grace, whereby we are received into the number, and have a right to all the privileges, of the sons of God.",
    refs: ["1 John 3:1", "John 1:12", "Rom. 8:17"],
  },
  {
    q: "What is sanctification?",
    a: "Sanctification is the work of God’s free grace, whereby we are renewed in the whole man after the image of God, and are enabled more and more to die unto sin, and live unto righteousness.",
    refs: ["2 Thess. 2:13", "Eph. 4:23-24", "Rom. 6:4, 6", "Rom. 8:1"],
  },
  {
    q: "What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?",
    a: "The benefits which in this life do accompany or flow from justification, adoption, and sanctification, are, assurance of God’s love, peace of conscience, joy in the Holy Ghost, increase of grace, and perseverance therein to the end.",
    refs: ["Rom. 5:1-2, 5", "Rom. 14:17", "Prov. 4:18", "1 John 5:13", "1 Pet. 1:5"],
  },
  {
    q: "What benefits do believers receive from Christ at death?",
    a: "The souls of believers are, at their death, made perfect in holiness, and do immediately pass into glory; and their bodies, being still united to Christ, do rest in their graves until the resurrection.",
    refs: [
      "Heb. 12:23",
      "2 Cor. 5:1, 6, 8",
      "Phil. 1:23",
      "Luke 23:43",
      "1 Thess. 4:14",
      "Isa. 57:2",
      "Job 19:26-27",
    ],
  },
  {
    q: "What benefits do believers receive from Christ at the resurrection?",
    a: "At the resurrection, believers, being raised up to glory, shall be openly acknowledged and acquitted in the day of judgment, and made perfectly blessed in the full enjoying of God to all eternity.",
    refs: [
      "1 Cor. 15:43",
      "Matt. 25:23",
      "Matt. 10:32",
      "1 John 3:2",
      "1 Cor. 13:12",
      "1 Thess. 4:17-18",
    ],
  },
  {
    q: "What is the duty which God requires of man?",
    a: "The duty which God requires of man, is obedience to his revealed will.",
    refs: ["Mic. 6:8", "1 Sam. 15:22"],
  },
  {
    q: "What did God at first reveal to man for the rule of his obedience?",
    a: "The rule which God at first revealed to man for his obedience, was the moral law.",
    refs: ["Rom. 2:14-15", "Rom. 10:5"],
  },
  {
    q: "Where is the moral law summarily comprehended?",
    a: "The moral law is summarily comprehended in the ten commandments.",
    refs: ["Deut. 10:4", "Matt. 19:17"],
  },
  {
    q: "What is the sum of the ten commandments?",
    a: "The sum of the ten commandments is, to love the Lord our God, with all our heart, with all our soul, with all our strength, and with all our mind; and our neighbor as ourselves.",
    refs: ["Matt. 22:37-40"],
  },
  {
    q: "What is the preface to the ten commandments?",
    a: "The preface to the ten commandments is in these words, \"I am the Lord your God, which have brought you out of the land of Egypt, out of the house of bondage.\"",
    refs: ["Ex. 20:2"],
  },
  {
    q: "What does the preface to the ten commandments teach us?",
    a: "The preface to the ten commandments teaches us, that because God is the Lord, and our God, and Redeemer, therefore we are bound to keep all his commandments.",
    refs: ["Luke 1:74-75", "1 Pet. 1:15-19"],
  },
  {
    q: "Which is the first commandment?",
    a: "The first commandment is, You shall have no other gods before me.",
    refs: ["Ex. 20:3"],
  },
  {
    q: "What is required in the first commandment?",
    a: "The first commandment requires us to know and acknowledge God to be the only true God, and our God, and to worship and glorify him accordingly.",
    refs: ["1 Chr 28:9", "Deut. 26:17", "Matt. 4:10", "Ps. 29:2"],
  },
  {
    q: "What is forbidden in the first commandment?",
    a: "The first commandment forbids the denying, or not worshipping and glorifying, the true God as God, and our God; and the giving of that worship and glory to any other, which is due to him alone.",
    refs: ["Ps. 14:1", "Rom. 1:21", "Ps. 81:10-11", "Rom. 1:25-26"],
  },
  {
    q: "What are we specially taught by these words, \"before me,\" in the first commandment?",
    a: "These words, \"before me,\" in the first commandment teach us, that God, who sees all things, takes notice of, and is much displeased with, the sin of having any other God.",
    refs: ["Ezek. 8:5-18", "Ps. 44:20-21"],
  },
  {
    q: "Which is the second commandment?",
    a: "The second commandment is, You shall not make unto you any graven image, or any likeness of anything that is in heaven above, or that is in the earth beneath, or that is in the water under the earth; you shall not bow down yourself to them, nor serve them; for I the Lord your God am a jealous God, visiting the iniquity of the fathers upon the children unto the third and fourth generation of them that hate me: and showing mercy unto thousands of them that love me, and keep my commandments.",
    refs: ["Ex. 20:4-6"],
  },
  {
    q: "What is required in the second commandment?",
    a: "The second commandment requires the receiving, observing, and keeping pure and entire, all such religious worship and ordinances as God has appointed in his Word.",
    refs: ["Deut. 32:46", "Matt. 28:20", "Acts 2:42"],
  },
  {
    q: "What is forbidden in the second commandment?",
    a: "The second commandment forbids the worshipping of God by images, or any other way not appointed in his Word.",
    refs: ["Deut. 4:15-19", "Ex. 32:5, 8", "Deut. 12:31-32"],
  },
  {
    q: "What are the reasons annexed to the second commandment?",
    a: "The reasons annexed to the second commandment are, God’s sovereignty over us, his propriety in us, and the zeal he has to his own worship.",
    refs: ["Ps. 95:2-3, 6", "Ps. 45:11", "Ex. 34:13-14"],
  },
  {
    q: "Which is the third commandment?",
    a: "The third commandment is, You shall not take the name of the Lord your God in vain: for the Lord will not hold him guiltless that takes his name in vain.",
    refs: ["Ex. 20:7"],
  },
  {
    q: "What is required in the third commandment?",
    a: "The third commandment requires the holy and reverent use of God’s names, titles, attributes, ordinances, word, and works.",
    refs: [
      "Matt. 6:9",
      "Deut. 28:58",
      "Ps. 68:4",
      "Rev. 15:3-4",
      "Mal. 1:11, 14",
      "Ps. 138:1-2",
      "Job 36:24",
    ],
  },
  {
    q: "What is forbidden in the third commandment?",
    a: "The third commandment forbids all profaning or abusing of anything whereby God makes himself known.",
    refs: ["Mal. 1:6-7, 12", "Mal. 2:2", "Mal. 3:14"],
  },
  {
    q: "What is the reason annexed to the third commandment?",
    a: "The reason annexed to the third commandment is, that however the breakers of this commandment may escape punishment from men, yet the Lord our God will not suffer them to escape his righteous judgment.",
    refs: ["1 Sam. 2:12, 17, 22, 29", "1 Sam. 3:13", "Deut. 28:58-59"],
  },
  {
    q: "Which is the fourth commandment?",
    a: "The fourth commandment is, Remember the Sabbath day, to keep it holy. Six days you shall labor, and do all your work: but the seventh day is the Sabbath of the Lord your God: in it you shall not do any work, you, nor your son, nor your daughter, your man-servant, nor your maid-servant, nor your cattle, nor your stranger that is within your gates: for in six days the Lord made heaven and earth, the sea, and all that in them is, and rested the seventh day: wherefore the Lord blessed the Sabbath-day, and hallowed it.",
    refs: ["Ex. 20:8-11"],
  },
  {
    q: "What is required in the fourth commandment?",
    a: "The fourth commandment requires the keeping holy to God such set times as he has appointed in his Word; expressly one whole day in seven, to be a holy Sabbath to himself.",
    refs: ["Deut. 5:12-14"],
  },
  {
    q: "Which day of the seven has God appointed to be the weekly Sabbath?",
    a: "From the beginning of the world to the resurrection of Christ, God appointed the seventh day of the week to be the weekly Sabbath; and the first day of the week, ever since, to continue to the end of the world, which is the Christian Sabbath.",
    refs: ["Gen. 2:2-3", "1 Cor. 16:1-2", "Acts 20:7"],
  },
  {
    q: "How is the Sabbath to be sanctified?",
    a: "The Sabbath is to be sanctified by a holy resting all that day, even from such worldly employments and recreations as are lawful on other days; and spending the whole time in the public and private exercises of God’s worship, except so much as is to be taken up in the works of necessity and mercy.",
    refs: [
      "Ex. 20:8, 10",
      "Ex. 16:25-28",
      "Neh. 13:15-19, 21-22",
      "Luke 4:16",
      "Acts 20:7",
      "Ps. 92 title",
      "Isa. 66:23",
      "Matt. 12:1-13",
    ],
  },
  {
    q: "What is forbidden in the fourth commandment?",
    a: "The fourth commandment forbids the omission, or careless performance, of the duties required, and the profaning the day by idleness, or doing that which is in itself sinful, or by unnecessary thoughts, words, or works, about our worldly employments or recreations.",
    refs: [
      "Ezek. 22:26",
      "Amos 8:5",
      "Mal. 1:13",
      "Acts 20:7, 9",
      "Ezek. 23:38",
      "Jer. 17:24-26",
      "Isa. 58:13",
    ],
  },
  {
    q: "What are the reasons annexed to the fourth commandment?",
    a: "The reasons annexed to the fourth commandment are, God’s allowing us six days of the week for our own employments, his challenging a special propriety in the seventh, his own example, and his blessing the Sabbath day.",
    refs: ["Ex. 20:9, 11"],
  },
  {
    q: "Which is the fifth commandment?",
    a: "The fifth commandment is, Honor your father and your mother: that your days may be long upon the land which the Lord your God gives you.",
    refs: ["Ex. 20:12"],
  },
  {
    q: "What is required in the fifth commandment?",
    a: "The fifth commandment requires the preserving the honor, and performing the duties, belonging to every one in their several places and relations, as superiors, inferiors, or equals.",
    refs: ["Eph. 5:21", "1 Pet. 2:17", "Rom. 12:10"],
  },
  {
    q: "What is forbidden in the fifth commandment?",
    a: "The fifth commandment forbids the neglecting of, or doing anything against, the honor and duty which belongs to every one in their several places and relations.",
    refs: ["Matt. 15:4-6", "Ezek. 34:2-4", "Rom. 13:8"],
  },
  {
    q: "What is the reason annexed to the fifth commandment?",
    a: "The reason annexed to the fifth commandment is, a promise of long life and prosperity (as far as it shall serve for God’s glory, and their own good) to all such as keep this commandment.",
    refs: ["Deut. 5:16", "Eph. 6:2-3"],
  },
  {
    q: "Which is the sixth commandment?",
    a: "The sixth commandment is, You shall not kill.",
    refs: ["Ex. 20:13"],
  },
  {
    q: "What is required in the sixth commandment?",
    a: "The sixth commandment requires all lawful endeavours to preserve our own life, and the life of others.",
    refs: ["Eph. 5:28-29", "1 Kings 18:4"],
  },
  {
    q: "What is forbidden in the sixth commandment?",
    a: "The sixth commandment forbids the taking away of our own life, or the life of our neighbor unjustly, or whatsoever tends thereunto.",
    refs: ["Acts 16:28", "Gen. 9:6"],
  },
  {
    q: "What is the seventh commandment?",
    a: "The seventh commandment is, You shall not commit adultery.",
    refs: ["Ex. 20:14"],
  },
  {
    q: "What is required in the seventh commandment?",
    a: "The seventh commandment requires the preservation of our own and our neighbor’s chastity, in heart, speech, and behaviour.",
    refs: ["1 Cor. 7:2-3, 5, 34, 36", "Col. 4:6", "1 Pet. 3:2"],
  },
  {
    q: "What is forbidden in the seventh commandment?",
    a: "The seventh commandment forbids all unchaste thoughts, words, and actions.",
    refs: ["Matt. 15:19", "Matt. 5:28", "Eph. 5:3-4"],
  },
  {
    q: "Which is the eighth commandment?",
    a: "The eighth commandment is, You shall not steal.",
    refs: ["Ex. 20:15"],
  },
  {
    q: "What is required in the eighth commandment?",
    a: "The eighth commandment requires the lawful procuring and furthering the wealth and outward estate of ourselves and others.",
    refs: [
      "Gen. 30:30",
      "1 Tim. 5:8",
      "Lev. 25:35",
      "Deut. 22:1-5",
      "Ex. 23:4-5",
      "Gen. 47:14, 20",
    ],
  },
  {
    q: "What is forbidden in the eighth commandment?",
    a: "The eighth commandment forbids whatsoever does, or may, unjustly hinder our own, or our neighbor’s, wealth, or outward estate.",
    refs: ["Prov. 21:17", "Prov. 23:20-21", "Prov. 28:19", "Eph. 4:28"],
  },
  {
    q: "Which is the ninth commandment?",
    a: "The ninth commandment is, You shall not bear false witness against your neighbor.",
    refs: ["Ex. 20:16"],
  },
  {
    q: "What is required in the ninth commandment?",
    a: "The ninth commandment requires the maintaining and promoting of truth between man and man, and of our own and our neighbor’s good name, especially in witness bearing.",
    refs: ["Zech. 8:16", "3 John 1:12", "Prov. 14:5, 25"],
  },
  {
    q: "What is forbidden in the ninth commandment?",
    a: "The ninth commandment forbids whatsoever is prejudicial to truth, or injurious to our own or our neighbor’s good name.",
    refs: ["1 Sam. 17:28", "Lev. 19:16", "Ps. 15:3"],
  },
  {
    q: "Which is the tenth commandment?",
    a: "The tenth commandment is, You shall not covet your neighbor’s house, you shall not covet your neighbor’s wife, nor his man-servant, nor his maid-servant, nor his ox, nor his ass, nor anything that is your neighbor’s.",
    refs: ["Ex. 20:17"],
  },
  {
    q: "What is required in the tenth commandment?",
    a: "The tenth commandment requires full contentment with our own condition, with a right and charitable frame of spirit toward our neighbor, and all that is his.",
    refs: [
      "Heb. 13:5",
      "1 Tim. 6:6",
      "Job 31:29",
      "Rom. 12:15",
      "1 Tim. 1:5",
      "1 Cor. 13:4-7",
    ],
  },
  {
    q: "What is forbidden in the tenth commandment?",
    a: "The tenth commandment forbids all discontentment with our own estate, envying or grieving at the good of our neighbor, and all inordinate motions and affections to anything that is his.",
    refs: [
      "1 Kings 21:4",
      "Esther 5:13",
      "1 Cor. 10:10",
      "Gal. 5:26",
      "Jas. 3:14, 16",
      "Rom. 7:7-8",
      "Rom. 13:9",
      "Deut. 5:21",
    ],
  },
  {
    q: "Is any man able perfectly to keep the commandments of God?",
    a: "No mere man since the fall is able in this life perfectly to keep the commandments of God, but does daily break them in thought, word, and deed.",
    refs: [
      "Ecc. 7:20",
      "1 John 1:8, 10",
      "Gal. 5:17",
      "Gen. 6:5",
      "Gen. 8:21",
      "Rom. 3:9-21",
      "Jas. 3:2-13",
    ],
  },
  {
    q: "Are all transgressions of the law equally heinous?",
    a: "Some sins in themselves, and by reason of several aggravations, are more heinous in the sight of God than others.",
    refs: ["Ezek. 8:6, 13, 15", "1 John 5:16", "Ps. 78:17, 32, 56"],
  },
  {
    q: "What does every sin deserve?",
    a: "Every sin deserves God’s wrath and curse, both in this life, and that which is to come.",
    refs: ["Eph. 5:6", "Gal. 3:10", "Lam. 3:39", "Matt. 25:41"],
  },
  {
    q: "What does God require of us, that we may escape his wrath and curse, due to us for sin?",
    a: "To escape the wrath and curse of God, due to us for sin, God requires of us faith in Jesus Christ, repentance unto life, with the diligent use of all the outward means whereby Christ communicates to us the benefits of redemption.",
    refs: ["Acts 20:21", "Prov. 2:1-5", "Prov. 8:33-36", "Isa. 55:3"],
  },
  {
    q: "What is faith in Jesus Christ?",
    a: "Faith in Jesus Christ is a saving grace, whereby we receive and rest upon him alone for salvation, as he is offered to us in the gospel.",
    refs: ["Heb. 10:39", "John 1:12", "Isa. 26:3-4", "Phil. 3:9", "Gal. 2:16"],
  },
  {
    q: "What is repentance unto life?",
    a: "Repentance unto life is a saving grace, whereby a sinner, out of a true sense of his sin, and apprehension of the mercy of God in Christ, does, with grief and hatred of his sin, turn from it unto God, with full purpose of, and endeavor after, new obedience.",
    refs: [
      "Acts 11:18",
      "Acts 2:37-38",
      "Joel 2:12",
      "Jer. 3:22",
      "Jer. 31:18-19",
      "Ezek. 36:31",
      "2 Cor. 7:11",
      "Isa. 1:16-17",
    ],
  },
  {
    q: "What are the outward and ordinary means whereby Christ communicates to us the benefits of redemption?",
    a: "The outward and ordinary means whereby Christ communicates to us the benefits of redemption are, his ordinances, especially the Word, Sacraments, and prayer; all which are made effectual to the elect for salvation.",
    refs: ["Matt. 28:19-20", "Acts 2:42, 46-47"],
  },
  {
    q: "How is the Word made effectual to salvation?",
    a: "The Spirit of God makes the reading, but especially the preaching, of the Word, an effectual means of convincing and converting sinners, and of building them up in holiness and comfort through faith unto salvation.",
    refs: [
      "Neh. 8:8",
      "1 Cor. 14:24-25",
      "Acts 26:18",
      "Ps. 19:8",
      "Acts 20:32",
      "Rom. 15:4",
      "2 Tim. 3:15-17",
      "Rom. 10:13-17",
      "Rom. 1:16",
    ],
  },
  {
    q: "How is the Word to be read and heard, that it may become effectual to salvation?",
    a: "That the Word may become effectual to salvation, we must attend thereunto with diligence, preparation, and prayer; receive it with faith and love, lay it up in our hearts, and practice it in our lives.",
    refs: [
      "Prov. 8:34",
      "1 Pet. 2:1-2",
      "Ps. 119:18",
      "Heb. 4:2",
      "2 Thess. 2:10",
      "Ps. 119:11",
      "Luke 8:15",
      "Jas. 1:25",
    ],
  },
  {
    q: "How do the Sacraments become effectual means of salvation?",
    a: "The Sacraments become effectual means of salvation, not from any virtue in them, or in him that does administer them; but only by the blessing of Christ, and the working of his Spirit in them that by faith receive them.",
    refs: ["1 Pet. 3:21", "Matt. 3:11", "1 Cor. 3:6-7", "1 Cor. 12:13"],
  },
  {
    q: "What is a Sacrament?",
    a: "A Sacrament is a holy ordinance instituted by Christ; wherein, by sensible signs, Christ and the benefits of the new covenant are represented, sealed, and applied to believers.",
    refs: ["Gen. 17:7, 10", "Ex. 12", "1 Cor. 11:23, 26"],
  },
  {
    q: "Which are the Sacraments of the New Testament?",
    a: "The Sacraments of the New Testament are Baptism, and the Lord’s Supper.",
    refs: ["Matt. 28:19", "Matt. 26:26-28"],
  },
  {
    q: "What is Baptism?",
    a: "Baptism is a Sacrament, wherein the washing with water, in the name of the Father, and of the Son, and of the Holy Ghost, does signify and seal our ingrafting into Christ, and partaking of the benefits of the covenant of grace, and our engagement to be the Lord’s.",
    refs: ["Matt. 28:19", "Rom. 6:4", "Gal. 3:27"],
  },
  {
    q: "To whom is Baptism to be administered?",
    a: "Baptism is not to be administered to any that are out of the visible Church, till they profess their faith in Christ, and obedience to him; but the infants of such as are members of the visible Church are to be baptized.",
    refs: [
      "Acts 8:36-37",
      "Acts 2:38-39",
      "Gen. 17:10",
      "Col. 2:11-12",
      "1 Cor. 7:14",
    ],
  },
  {
    q: "What is the Lord’s Supper?",
    a: "The Lord’s Supper is a Sacrament, wherein, by giving and receiving bread and wine, according to Christ’s appointment, his death is showed forth; and the worthy receivers are, not after a corporal and carnal manner, but by faith, made partakers of his body and blood, with all his benefits, to their spiritual nourishment and growth in grace.",
    refs: ["1 Cor. 11:23-26", "1 Cor. 10:16"],
  },
  {
    q: "What is required to the worthy receiving of the Lord’s Supper?",
    a: "It is required of them that would worthily partake of the Lord’s Supper, that they examine themselves, of their knowledge to discern the Lord’s body, of their faith to feed upon him, of their repentance, love, and new obedience; lest, coming unworthily, they eat and drink judgment to themselves.",
    refs: [
      "1 Cor. 11:28-29",
      "2 Cor. 13:5",
      "1 Cor. 11:31",
      "1 Cor. 10:16-17",
      "1 Cor. 5:7-8",
    ],
  },
  {
    q: "What is prayer?",
    a: "Prayer is an offering up of our desires unto God, for things agreeable to his will, in the name of Christ, with confession of our sins, and thankful acknowledgment of his mercies.",
    refs: ["Ps. 62:8", "1 John 5:14", "John 16:23", "Ps. 32:5-6", "Dan. 9:4", "Phil. 4:6"],
  },
  {
    q: "What rule has God given for our direction in prayer?",
    a: "The whole Word of God is of use to direct us in prayer, but the special rule of direction is that form of prayer which Christ taught his disciples, commonly called, The Lord’s Prayer.",
    refs: ["1 John 5:14", "Matt. 6:9-13", "Luke 11:2-4"],
  },
  {
    q: "What does the preface of the Lord’s Prayer teach us?",
    a: "The preface of the Lord’s Prayer, which is, \"Our Father which art in heaven,\" teaches us to draw near to God with all holy reverence and confidence, as children to a father, able and ready to help us; and that we should pray with and for others.",
    refs: ["Matt. 6:9", "Rom. 8:15", "Luke 11:13", "Acts 12:5", "1 Tim. 2:1-2"],
  },
  {
    q: "What do we pray for in the first petition?",
    a: "In the first petition, which is, \"Hallowed be your name,\" we pray, that God would enable us, and others, to glorify him in all that whereby he makes himself known, and that he would dispose all things to his own glory.",
    refs: ["Matt. 6:9", "Ps. 67:2-3", "Ps. 83"],
  },
  {
    q: "What do we pray for in the second petition?",
    a: "In the second petition, which is, \"Your kingdom come,\" we pray, that Satan’s kingdom may be destroyed; and that the kingdom of grace may be advanced, ourselves and others brought into it, and kept in it; and that the kingdom of glory may be hastened.",
    refs: [
      "Matt. 6:10",
      "Ps. 68:1, 18",
      "Rev. 12:10-11",
      "2 Thess. 3:1",
      "Rom. 10:1",
      "John 17:9,20",
      "Rev. 22:20",
    ],
  },
  {
    q: "What do we pray for in the third petition?",
    a: "In the third petition, which is, \"Your will be done in earth as it is in heaven,\" we pray, that God, by his grace, would make us able and willing to know, obey, and submit to his will in all things, as the angels do in heaven.",
    refs: ["Matt. 6:10", "Ps. 67", "Ps. 119:36", "Matt. 26:39", "2 Sam. 15:25", "Job. 1:21", "Ps. 103:20-21"],
  },
  {
    q: "What do we pray for in the fourth petition?",
    a: "In the fourth petition, which is, \"Give us this day our daily bread,\" we pray, that of God’s free gift we may receive a competent portion of the good things of this life, and enjoy his blessing with them.",
    refs: ["Matt. 6:11", "Prov. 30:8-9", "Gen. 28:20", "1 Tim. 4:4-5"],
  },
  {
    q: "What do we pray for in the fifth petition?",
    a: "In the fifth petition, which is, \"And forgive us our debts, as we forgive our debtors,\" we pray, that God, for Christ’s sake, would freely pardon all our sins; which we are the rather encouraged to ask, because by his grace we are enabled from the heart to forgive others.",
    refs: ["Matt. 6:12", "Ps. 51:1-2, 7, 9", "Dan. 9:17-19", "Luke 11:4", "Matt. 18:35"],
  },
  {
    q: "What do we pray for in the sixth petition?",
    a: "In the sixth petition, which is, \"And lead us not into temptation, but deliver us from evil,\" we pray, that God would either keep us from being tempted to sin, or support and deliver us when we are tempted.",
    refs: ["Matt. 6:12", "Matt. 26:41", "2 Cor. 12:7-8"],
  },
  {
    q: "What does the conclusion of the Lord’s Prayer teach us?",
    a: "The conclusion of the Lord’s Prayer, which is, \"For yours is the kingdom, and the power, and the glory, for ever. Amen,\" teaches us to take our encouragement in prayer from God only, and in our prayers to praise him, ascribing kingdom, power, and glory to him; and in testimony of our desire and assurance to be heard, we say, Amen.",
    refs: [
      "Matt. 6:13",
      "Dan. 9:4-9, 16-19",
      "1 Chr 29:10-13",
      "1 Cor. 14:16",
      "Rev. 22:20-21",
    ],
  },
];

